export type DocType = "docx" | "pptx";

export type IssueCategory = "contrast" | "font" | "alt" | "heading";
export type IssueSeverity = "critical" | "warning" | "info";

export interface Issue {
  id: string;
  category: IssueCategory;
  severity: IssueSeverity;
  title: string;
  location: string;
  detail?: string;
  suggestion?: string;
  // Contrast-specific fields
  fg?: string;
  bg?: string;
  ratio?: string;
  required?: string;
  /**
   * Optional visual preview of the problem area — a snippet from the user's
   * document rendered with its detected formatting (Calibri-family font,
   * detected colors + size + weight). Captured by the real DOCX analyzer;
   * older mock issues won't have this.
   */
  preview?: IssuePreview;
  resolved: boolean;
}

export interface IssuePreview {
  /** The actual text from the user's document */
  text: string;
  /** Normalized hex foreground color, e.g. "#e6e6e6" */
  fg?: string;
  /** Normalized hex background color, e.g. "#ffffff" */
  bg?: string;
  /** Font size in points, e.g. 11 or 8 */
  sizePt?: number;
  /** The detected font family name (e.g. "Calibri", "Arial", "Times New Roman") */
  fontFamily?: string;
  bold?: boolean;
  italic?: boolean;
  /** For heading issues: the detected heading level (1-9) */
  headingLevel?: number;
}

export interface ReviewVersion {
  version: number;
  reviewedAt: string;
  score: number;
  issues: Issue[];
  /** Number resolved since the previous version */
  resolvedSinceLast?: number;
}

export interface Document {
  id: string;
  name: string;
  type: DocType;
  size: string;
  uploadedAt: string;
  versions: ReviewVersion[];
}

export const ISSUE_CATEGORY_META: Record<
  IssueCategory,
  { label: string; description: string }
> = {
  contrast: {
    label: "Color contrast",
    description:
      "Text does not meet the WCAG 2.1 minimum contrast ratio against its background.",
  },
  font: {
    label: "Font size",
    description: "Text is smaller than recommended for accessible reading.",
  },
  alt: {
    label: "Missing alt text",
    description:
      "Images are missing descriptive alternative text for screen readers.",
  },
  heading: {
    label: "Heading structure",
    description: "Headings are missing, mis-ordered, or skip levels.",
  },
};

export const SEVERITY_ORDER: Record<IssueSeverity, number> = {
  critical: 0,
  warning: 1,
  info: 2,
};

// ---------- Adobe Accessibility Report reviews ----------

/**
 * Status of a single rule in an Adobe Accessibility Report. Adobe uses
 * "Passed", "Failed", "Needs manual check", "Skipped", "Not applicable" —
 * we normalize those to three buckets here.
 */
export type PdfRuleStatus = "failed" | "needs-check" | "passed" | "not-applicable";

export interface PdfFinding {
  id: string;
  /** Broad category from the Adobe report, e.g. "Document", "Page content" */
  category: string;
  /** Specific rule name, e.g. "Tagged PDF", "Logical Reading Order" */
  rule: string;
  status: PdfRuleStatus;
  /** The raw description/why text from the Adobe report (when available). */
  description?: string;
  /**
   * Plain-language, tool-agnostic suggestion for what to change in the source
   * file so this rule passes on the next export. Generated by the suggestion
   * library in lib/adobe-suggestions.ts.
   */
  suggestion: string;
  /** Whether the user has marked this finding as resolved (UI state). */
  resolved: boolean;
}

export interface PdfReview {
  id: string;
  pdfName: string;
  reportName: string;
  /** How big the original PDF was — shown in the dashboard row. */
  pdfSize: string;
  uploadedAt: string;
  /** Rough score: 100 minus weighted deductions for failures + manual checks. */
  score: number;
  findings: PdfFinding[];
}

